DROP TABLE IF EXISTS user_logs;
DROP TABLE IF EXISTS user_groups;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS user_login_attempts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tenants;
