version: "2"
linters:
  enable:
    - varnamelen
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dupl
    - dupword
    - err113
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gosec
    - whitespace
    - wsl
  settings:
    varnamelen:
      ignore-names:
        - ok
        - id
        - db
        - i
      ignore-decls:
        - r *http.Request
        - w http.ResponseWriter
        - v *validation.Validator
        - tx *sql.Tx
        - tx dbutils.DB
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
          - varnamelen
          - cyclop
          - forcetypeassert
          - gocognit
