version: "2"
linters:
  enable:
    - varnamelen
    - funlen
  settings:
    varnamelen:
      ignore-names:
        - ok
        - id
        - db
        - i
      ignore-decls:
        - r *http.Request
        - w http.ResponseWriter
        - v *validation.Validator
        - tx *sql.Tx
        - tx dbutils.DB
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
          - varnamelen
